<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BansosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bansos')->insert([
            [
                'keluarga_id' => 1,
                'K1' => 4,
                'K2' => 3,
                'K3' => 1,
                'K4' => 1,
                'K5' => 3,
                'K6' => 5,
                'K7' => 1,
                'K8' => 3,
                'K9' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' => 2,
                'K1' => 5,
                'K2' => 4,
                'K3' => 2,
                'K4' => 2,
                'K5' => 1,
                'K6' => 2,
                'K7' => 1,
                'K8' => 2,
                'K9' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' => 3,
                'K1' => 3,
                'K2' => 3,
                'K3' => 2,
                'K4' => 3,
                'K5' => 3,
                'K6' => 4,
                'K7' => 1,
                'K8' => 3,
                'K9' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' => 4,
                'K1' => 4,
                'K2' => 5,
                'K3' => 2,
                'K4' => 3,
                'K5' => 2,
                'K6' => 2,
                'K7' => 1,
                'K8' => 4,
                'K9' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' => 5,
                'K1' => 5,
                'K2' => 5,
                'K3' => 1,
                'K4' => 3,
                'K5' => 3,
                'K6' => 3,
                'K7' => 1,
                'K8' => 3,
                'K9' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' => 6,
                'K1' => 2,
                'K2' => 3,
                'K3' => 2,
                'K4' => 3,
                'K5' => 2,
                'K6' => 2,
                'K7' => 2,
                'K8' => 2,
                'K9' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' => 7,
                'K1' => 4,
                'K2' => 5,
                'K3' => 1,
                'K4' => 3,
                'K5' => 1,
                'K6' => 5,
                'K7' => 1,
                'K8' => 2,
                'K9' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' => 8,
                'K1' => 3,
                'K2' => 4,
                'K3' => 2,
                'K4' => 2,
                'K5' => 3,
                'K6' => 4,
                'K7' => 1,
                'K8' => 3,
                'K9' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' =>9,
                'K1' => 3,
                'K2' => 5,
                'K3' => 2,
                'K4' => 2,
                'K5' => 3,
                'K6' => 3,
                'K7' => 1,
                'K8' => 4,
                'K9' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'keluarga_id' => 10,
                'K1' => 4,
                'K2' => 2,
                'K3' => 2,
                'K4' => 3,
                'K5' => 3,
                'K6' => 5,
                'K7' => 2,
                'K8' => 4,
                'K9' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
