<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $usersData = [
            // [
            //     'nik' => 123456789,
            //     'nama' => 'John Doe',
            //     'tgl_lahir' => '1990-05-15',
            //     'tempat_lahir' => 'Jakarta',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 1, // ID Agama_id Islam
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Karyawan',
            //     'notelp' => '08123456789',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 987654321,
            //     'nama' => 'Jane Doe',
            //     'tgl_lahir' => '1992-08-20',
            //     'tempat_lahir' => 'Bandung',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 2, // ID Agama_id Kristen Protestan
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Mahasiswa',
            //     'notelp' => '08567891234',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 111222333,
            //     'nama' => 'Ahmad Abdullah',
            //     'tgl_lahir' => '1988-04-10',
            //     'tempat_lahir' => 'Surabaya',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 1, // ID Agama_id Islam
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Guru',
            //     'notelp' => '08765432100',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 444555666,
            //     'nama' => 'Siti Rahayu',
            //     'tgl_lahir' => '1995-12-03',
            //     'tempat_lahir' => 'Yogyakarta',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 3, // ID Agama_id Katolik
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Wiraswasta',
            //     'notelp' => '08112233445',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 777888999,
            //     'nama' => 'Budi Santoso',
            //     'tgl_lahir' => '1985-10-25',
            //     'tempat_lahir' => 'Medan',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 4, // ID Agama_id Hindu
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Dosen',
            //     'notelp' => '08987654321',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 333222111,
            //     'nama' => 'Rina Wati',
            //     'tgl_lahir' => '1998-06-15',
            //     'tempat_lahir' => 'Semarang',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 2, // ID Agama_id Kristen Protestan
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Pelajar',
            //     'notelp' => '08123456789',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 666777888,
            //     'nama' => 'Agus Setiawan',
            //     'tgl_lahir' => '1987-03-18',
            //     'tempat_lahir' => 'Surakarta',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 5, // ID Agama_id Buddha
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Wiraswasta',
            //     'notelp' => '08765432100',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 222333444,
            //     'nama' => 'Linda Susanti',
            //     'tgl_lahir' => '1994-09-28',
            //     'tempat_lahir' => 'Malang',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 1, // ID Agama_id Islam
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Pegawai Negeri',
            //     'notelp' => '08211223344',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 555444333,
            //     'nama' => 'Dedi Firmansyah',
            //     'tgl_lahir' => '1993-02-12',
            //     'tempat_lahir' => 'Pontianak',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 3, // ID Agama_id Katolik
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Pengusaha',
            //     'notelp' => '08987654321',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 999888777,
            //     'nama' => 'Rini Cahyani',
            //     'tgl_lahir' => '1997-11-05',
            //     'tempat_lahir' => 'Bandar Lampung',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 4, // ID Agama_id Hindu
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Penulis',
            //     'notelp' => '08112233445',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 123321123,
            //     'nama' => 'Ani Fatimah',
            //     'tgl_lahir' => '1996-07-20',
            //     'tempat_lahir' => 'Makassar',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 5, // ID Agama_id Buddha
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Konsultan',
            //     'notelp' => '08761234567',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 456654456,
            //     'nama' => 'Fahmi Prasetyo',
            //     'tgl_lahir' => '1989-11-15',
            //     'tempat_lahir' => 'Surabaya',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 2, // ID Agama_id Kristen Protestan
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Manager',
            //     'notelp' => '08111223344',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 789987789,
            //     'nama' => 'Sari Indah',
            //     'tgl_lahir' => '1991-03-25',
            //     'tempat_lahir' => 'Denpasar',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 3, // ID Agama_id Katolik
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Dokter',
            //     'notelp' => '08233445566',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 987789987,
            //     'nama' => 'Andi Wijaya',
            //     'tgl_lahir' => '1990-01-10',
            //     'tempat_lahir' => 'Padang',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 4, // ID Agama_id Hindu
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Pengusaha',
            //     'notelp' => '08127894567',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 678987678,
            //     'nama' => 'Dina Wahyu',
            //     'tgl_lahir' => '1993-06-30',
            //     'tempat_lahir' => 'Bandung',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 5, // ID Agama_id Buddha
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Arsitek',
            //     'notelp' => '08761234567',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 987678987,
            //     'nama' => 'Eko Prasetyo',
            //     'tgl_lahir' => '1987-09-05',
            //     'tempat_lahir' => 'Surabaya',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 1, // ID Agama_id Islam
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Pegawai Swasta',
            //     'notelp' => '08127894567',
            //     'keluarga_id' => null,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'nik' => 135792468,
            //     'nama' => 'Rudi Hartono',
            //     'tgl_lahir' => '1994-02-28',
            //     'tempat_lahir' => 'Bandung',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 3, // ID Agama_id Katolik
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Konsultan IT',
            //     'notelp' => '08123456789',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 246813579,
            //     'nama' => 'Sari Wijaya',
            //     'tgl_lahir' => '1991-11-15',
            //     'tempat_lahir' => 'Yogyakarta',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 4, // ID Agama_id Hindu
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Arsitek',
            //     'notelp' => '08567891234',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 369258147,
            //     'nama' => 'Bambang Susanto',
            //     'tgl_lahir' => '1989-09-20',
            //     'tempat_lahir' => 'Surabaya',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 1, // ID Agama_id Islam
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Pengusaha',
            //     'notelp' => '08765432100',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 579312468,
            //     'nama' => 'Dewi Lestari',
            //     'tgl_lahir' => '1993-05-10',
            //     'tempat_lahir' => 'Semarang',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 2, // ID Agama_id Kristen Protestan
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Pelajar',
            //     'notelp' => '08112233445',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 789654123,
            //     'nama' => 'Tono Sutrisno',
            //     'tgl_lahir' => '1997-08-05',
            //     'tempat_lahir' => 'Bandung',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 5, // ID Agama_id Buddha
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Dokter',
            //     'notelp' => '08987654321',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 951753852,
            //     'nama' => 'Lina Cahyani',
            //     'tgl_lahir' => '1990-03-18',
            //     'tempat_lahir' => 'Surakarta',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 3, // ID Agama_id Katolik
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Pegawai Negeri',
            //     'notelp' => '08211223344',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 852741963,
            //     'nama' => 'Arief Budiman',
            //     'tgl_lahir' => '1988-12-10',
            //     'tempat_lahir' => 'Makassar',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 4, // ID Agama_id Hindu
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Pengusaha',
            //     'notelp' => '08127894567',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 369147258,
            //     'nama' => 'Linda Saputri',
            //     'tgl_lahir' => '1995-06-30',
            //     'tempat_lahir' => 'Denpasar',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 5, // ID Agama_id Buddha
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Arsitek',
            //     'notelp' => '08761234567',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 741258963,
            //     'nama' => 'Rudi Setiawan',
            //     'tgl_lahir' => '1992-04-25',
            //     'tempat_lahir' => 'Padang',
            //     'jenis_kelamin' => 'Laki',
            //     'agama_id' => 1, // ID Agama_id Islam
            //     'status_perkawinan' => 'Kawin',
            //     'pekerjaan' => 'Pegawai Swasta',
            //     'notelp' => '08127894567',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'nik' => 654789321,
            //     'nama' => 'Santi Wijaya',
            //     'tgl_lahir' => '1994-07-12',
            //     'tempat_lahir' => 'Surabaya',
            //     'jenis_kelamin' => 'Perempuan',
            //     'agama_id' => 2, // ID Agama_id Kristen Protestan
            //     'status_perkawinan' => 'Belum Kawin',
            //     'pekerjaan' => 'Manager',
            //     'notelp' => '08561234567',
            //     'keluarga_id' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

            // Family 1
            [
                'nik' => '3573070119600401',
                'nama' => 'Budi Hartono',
                'tgl_lahir' => '1960-04-01',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456789',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000408',
                'nama' => 'Sari Wijaya',
                'tgl_lahir' => '2000-04-08',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456790',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119700405',
                'nama' => 'Agus Susanto',
                'tgl_lahir' => '1970-04-05',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456791',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000415',
                'nama' => 'Lina Kurniawan',
                'tgl_lahir' => '2000-04-15',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456792',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 2
            [
                'nik' => '3573070119600502',
                'nama' => 'Dedi Firmansyah',
                'tgl_lahir' => '1960-05-02',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '08123456793',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000510',
                'nama' => 'Rina Sari',
                'tgl_lahir' => '2000-05-10',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456794',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800522',
                'nama' => 'Andi Jayawijaya',
                'tgl_lahir' => '1980-05-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'notelp' => '08123456795',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000528',
                'nama' => 'Dewi Susanti',
                'tgl_lahir' => '2000-05-28',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456796',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Family 3
            [
                'nik' => '3573070119700601',
                'nama' => 'Eko Prasetyo',
                'tgl_lahir' => '1970-06-01',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456797',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000609',
                'nama' => 'Ani Susanti',
                'tgl_lahir' => '2000-06-09',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456798',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800603',
                'nama' => 'Fahmi Prasetyo',
                'tgl_lahir' => '1980-06-03',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '08123456799',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000631',
                'nama' => 'Linda Kurniawan',
                'tgl_lahir' => '2000-06-30',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456800',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 4
            [
                'nik' => '3573070119600702',
                'nama' => 'Bambang Suryo',
                'tgl_lahir' => '1960-07-02',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456801',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000711',
                'nama' => 'Rini Wijaya',
                'tgl_lahir' => '2000-07-11',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456802',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800704',
                'nama' => 'Dodi Firmansyah',
                'tgl_lahir' => '1980-07-04',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'notelp' => '08123456803',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000722',
                'nama' => 'Siti Hartanti',
                'tgl_lahir' => '2000-07-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456804',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 5
            [
                'nik' => '3573070119600803',
                'nama' => 'Andi Susanto',
                'tgl_lahir' => '1960-08-03',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pegawai Negeri',
                'notelp' => '08123456805',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000812',
                'nama' => 'Dewi Susanti',
                'tgl_lahir' => '2000-08-12',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456806',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800815',
                'nama' => 'Eko Wijaya',
                'tgl_lahir' => '1980-08-15',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '08123456807',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000823',
                'nama' => 'Sari Rahayu',
                'tgl_lahir' => '2000-08-23',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456808',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 6
            [
                'nik' => '3573070119600904',
                'nama' => 'Agus Prasetyo',
                'tgl_lahir' => '1960-09-04',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456809',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000910',
                'nama' => 'Nina Kurniawati',
                'tgl_lahir' => '2000-09-10',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456810',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800917',
                'nama' => 'Bambang Suryanto',
                'tgl_lahir' => '1980-09-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456811',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000925',
                'nama' => 'Linda Susanto',
                'tgl_lahir' => '2000-09-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456812',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 7
            [
                'nik' => '3573070119601001',
                'nama' => 'Dedi Setiawan',
                'tgl_lahir' => '1960-10-01',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'notelp' => '08123456813',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001007',
                'nama' => 'Anita Wijayanti',
                'tgl_lahir' => '2000-10-07',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456814',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119801005',
                'nama' => 'Eko Santoso',
                'tgl_lahir' => '1980-10-05',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '08123456815',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001016',
                'nama' => 'Siti Rahmawati',
                'tgl_lahir' => '2000-10-16',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456816',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 8
            [
                'nik' => '3573070119601102',
                'nama' => 'Rudi Hartanto',
                'tgl_lahir' => '1960-11-02',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456817',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001113',
                'nama' => 'Dina Lestari',
                'tgl_lahir' => '2000-11-13',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456818',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119801118',
                'nama' => 'Fajar Nugroho',
                'tgl_lahir' => '1980-11-18',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456819',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001129',
                'nama' => 'Eva Kurniasari',
                'tgl_lahir' => '2000-11-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456820',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 9
            [
                'nik' => '3573070119601204',
                'nama' => 'Ganis Setiawan',
                'tgl_lahir' => '1960-12-04',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456821',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001210',
                'nama' => 'Hana Mariani',
                'tgl_lahir' => '2000-12-10',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456822',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119801225',
                'nama' => 'Iwan Kusuma',
                'tgl_lahir' => '1980-12-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '08123456823',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001231',
                'nama' => 'Juli Astuti',
                'tgl_lahir' => '2000-12-31',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456824',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 10
            [
                'nik' => '3573070119600110',
                'nama' => 'Kemal Pasha',
                'tgl_lahir' => '1960-01-10',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456825',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000102',
                'nama' => 'Karina Sulastri',
                'tgl_lahir' => '2000-01-02',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456826',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800120',
                'nama' => 'Lukman Hakim',
                'tgl_lahir' => '1980-01-20',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '08123456827',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000131',
                'nama' => 'Mila Kurniawati',
                'tgl_lahir' => '2000-01-31',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456828',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 11
            [
                'nik' => '3573070119600211',
                'nama' => 'Narpati Agung',
                'tgl_lahir' => '1960-02-11',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'notelp' => '08123456829',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000205',
                'nama' => 'Novi Ratnasari',
                'tgl_lahir' => '2000-02-05',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456830',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800228',
                'nama' => 'Omar Dani',
                'tgl_lahir' => '1980-02-28',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456831',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000230',
                'nama' => 'Putri Maharani',
                'tgl_lahir' => '2000-02-27',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456832',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 12
            [
                'nik' => '3573070119600312',
                'nama' => 'Priyo Suharto',
                'tgl_lahir' => '1960-03-12',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456833',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000306',
                'nama' => 'Rita Puspitasari',
                'tgl_lahir' => '2000-03-06',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456834',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800318',
                'nama' => 'Sigit Purnomo',
                'tgl_lahir' => '1980-03-18',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '08123456835',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000324',
                'nama' => 'Tina Melinda',
                'tgl_lahir' => '2000-03-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456836',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 13
            [
                'nik' => '3573070119600413',
                'nama' => 'Agus Septi',
                'tgl_lahir' => '1960-04-13',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456837',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000414',
                'nama' => 'Dewi Sartika',
                'tgl_lahir' => '2000-04-14',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456838',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800415',
                'nama' => 'Bambang Sudarsono',
                'tgl_lahir' => '1980-04-15',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456839',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000416',
                'nama' => 'Nina Wulandari',
                'tgl_lahir' => '2000-04-16',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456840',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 14
            [
                'nik' => '3573070119600514',
                'nama' => 'Yudi Prasetyo',
                'tgl_lahir' => '1960-05-14',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456841',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000515',
                'nama' => 'Sinta Dewi',
                'tgl_lahir' => '2000-05-15',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456842',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800516',
                'nama' => 'Anton Wahyudi',
                'tgl_lahir' => '1980-05-16',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '08123456843',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000517',
                'nama' => 'Rani Melati',
                'tgl_lahir' => '2000-05-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456844',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 15
            [
                'nik' => '3573070119600615',
                'nama' => 'Dwi Cahyono',
                'tgl_lahir' => '1960-06-15',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456845',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000616',
                'nama' => 'Citra Kirana',
                'tgl_lahir' => '2000-06-16',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456846',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800617',
                'nama' => 'Bimo Satrio',
                'tgl_lahir' => '1980-06-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456847',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000618',
                'nama' => 'Dian Sastrowardoyo',
                'tgl_lahir' => '2000-06-18',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456848',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 16
            [
                'nik' => '3573070119600716',
                'nama' => 'Eka Putra',
                'tgl_lahir' => '1960-07-16',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456849',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000717',
                'nama' => 'Fitri Handayani',
                'tgl_lahir' => '2000-07-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456850',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800718',
                'nama' => 'Gatot Kaca',
                'tgl_lahir' => '1980-07-18',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '08123456851',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000719',
                'nama' => 'Hani Rizki',
                'tgl_lahir' => '2000-07-19',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456852',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 17
            [
                'nik' => '3573070119600817',
                'nama' => 'Joko Widodo',
                'tgl_lahir' => '1960-08-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456853',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000818',
                'nama' => 'Karina Sari',
                'tgl_lahir' => '2000-08-18',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456854',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800819',
                'nama' => 'Laksamana Ryo',
                'tgl_lahir' => '1980-08-19',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456855',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000820',
                'nama' => 'Mira Anggraini',
                'tgl_lahir' => '2000-08-20',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456856',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 18
            [
                'nik' => '3573070119600918',
                'nama' => 'Nugroho Baskoro',
                'tgl_lahir' => '1960-09-18',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'notelp' => '08123456857',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000919',
                'nama' => 'Laila Putri',
                'tgl_lahir' => '2000-09-19',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456858',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800920',
                'nama' => 'Rendra Wijaya',
                'tgl_lahir' => '1980-09-20',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456859',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000921',
                'nama' => 'Sara Dewi',
                'tgl_lahir' => '2000-09-21',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456860',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 19
            [
                'nik' => '3573070119601022',
                'nama' => 'Bagas Kurniawan',
                'tgl_lahir' => '1960-10-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456861',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001023',
                'nama' => 'Tania Yusuf',
                'tgl_lahir' => '2000-10-23',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456862',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119801024',
                'nama' => 'Faris Rahmat',
                'tgl_lahir' => '1980-10-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '08123456863',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001025',
                'nama' => 'Dinda Larasati',
                'tgl_lahir' => '2000-10-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456864',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 20
            [
                'nik' => '3573070119601120',
                'nama' => 'Irfan Makki',
                'tgl_lahir' => '1960-11-20',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456865',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001121',
                'nama' => 'Umi Kalsum',
                'tgl_lahir' => '2000-11-21',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456866',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119801122',
                'nama' => 'Harun Al Rasyid',
                'tgl_lahir' => '1980-11-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456867',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001123',
                'nama' => 'Nadia Zulaikha',
                'tgl_lahir' => '2000-11-23',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456868',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 21
            [
                'nik' => '3573070119601221',
                'nama' => 'Johan Saputra',
                'tgl_lahir' => '1960-12-21',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456869',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001222',
                'nama' => 'Ayu Larasati',
                'tgl_lahir' => '2000-12-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456870',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119801224',
                'nama' => 'Bayu Dwi',
                'tgl_lahir' => '1980-12-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '08123456871',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001225',
                'nama' => 'Chintya Maulida',
                'tgl_lahir' => '2000-12-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456872',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 22
            [
                'nik' => '3573070119600122',
                'nama' => 'Reza Rahadian',
                'tgl_lahir' => '1960-01-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456873',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000123',
                'nama' => 'Mila Kunis',
                'tgl_lahir' => '2000-01-23',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456874',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800124',
                'nama' => 'Andi Arsyil',
                'tgl_lahir' => '1980-01-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456875',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000125',
                'nama' => 'Sari Nindita',
                'tgl_lahir' => '2000-01-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456876',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 23
            [
                'nik' => '3573070119600223',
                'nama' => 'Bimo Setiawan',
                'tgl_lahir' => '1960-02-23',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456877',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000224',
                'nama' => 'Tina Supriadi',
                'tgl_lahir' => '2000-02-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456878',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800225',
                'nama' => 'Arif Rahman',
                'tgl_lahir' => '1980-02-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '08123456879',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000226',
                'nama' => 'Nurul Hikmah',
                'tgl_lahir' => '2000-02-26',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456880',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 24
            [
                'nik' => '3573070119600324',
                'nama' => 'Dwi Cahyadi',
                'tgl_lahir' => '1960-03-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'notelp' => '08123456881',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000325',
                'nama' => 'Yuni Rahayu',
                'tgl_lahir' => '2000-03-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456882',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800326',
                'nama' => 'Galih Permadi',
                'tgl_lahir' => '1980-03-26',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '08123456883',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000327',
                'nama' => 'Putri Anggraini',
                'tgl_lahir' => '2000-03-27',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456884',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 25
            [
                'nik' => '3573070119600425',
                'nama' => 'Rudi Pratama',
                'tgl_lahir' => '1960-04-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '08123456885',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000426',
                'nama' => 'Vina Mariana',
                'tgl_lahir' => '2000-04-26',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456886',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800427',
                'nama' => 'Sandy Wahyu',
                'tgl_lahir' => '1980-04-27',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '08123456887',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000428',
                'nama' => 'Dian Sastro',
                'tgl_lahir' => '2000-04-28',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456888',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 26
            [
                'nik' => '3573070119600526',
                'nama' => 'Aliando Syarief',
                'tgl_lahir' => '1960-05-26',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '08123456889',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000527',
                'nama' => 'Bella Saphira',
                'tgl_lahir' => '2000-05-27',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '08123456890',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800528',
                'nama' => 'Cakra Khan',
                'tgl_lahir' => '1980-05-28',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Musisi',
                'notelp' => '08123456891',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000529',
                'nama' => 'Della Perez',
                'tgl_lahir' => '2000-05-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '08123456892',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 27
            [
                'nik' => '3573070119600627',
                'nama' => 'Eko Patrio',
                'tgl_lahir' => '1960-06-27',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Komika',
                'notelp' => '08123456893',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000628',
                'nama' => 'Fatin Shidqia',
                'tgl_lahir' => '2000-06-28',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Penyanyi',
                'notelp' => '08123456894',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800629',
                'nama' => 'Gading Marten',
                'tgl_lahir' => '1980-06-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456895',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000630',
                'nama' => 'Hesti Purwadinata',
                'tgl_lahir' => '2000-06-30',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Presenter',
                'notelp' => '08123456896',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 28
            [
                'nik' => '3573070119600728',
                'nama' => 'Indra Bekti',
                'tgl_lahir' => '1960-07-28',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Presenter',
                'notelp' => '08123456897',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000729',
                'nama' => 'Jessica Mila',
                'tgl_lahir' => '2000-07-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456898',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800730',
                'nama' => 'Arief Muhammad',
                'tgl_lahir' => '1980-07-30',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Influencer',
                'notelp' => '08123456899',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000731',
                'nama' => 'Karina Suwandi',
                'tgl_lahir' => '2000-07-31',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Model',
                'notelp' => '08123456900',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 29
            [
                'nik' => '3573070119600829',
                'nama' => 'Lukman Sardi',
                'tgl_lahir' => '1960-08-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456901',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000830',
                'nama' => 'Maudy Ayunda',
                'tgl_lahir' => '2000-08-30',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Penyanyi',
                'notelp' => '08123456902',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119800831',
                'nama' => 'Nino Fernandez',
                'tgl_lahir' => '1980-08-31',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456903',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000901',
                'nama' => 'Pevita Pearce',
                'tgl_lahir' => '2000-09-01',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456904',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Family 30
            [
                'nik' => '3573070119600930',
                'nama' => 'Reza Rahardian',
                'tgl_lahir' => '1960-09-30',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456905',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142000931',
                'nama' => 'Tara Basro',
                'tgl_lahir' => '2000-09-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456906',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070119801001',
                'nama' => 'Ario Bayu',
                'tgl_lahir' => '1980-10-01',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456907',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070142001002',
                'nama' => 'Adinia Wirasti',
                'tgl_lahir' => '2000-10-02',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Aktor',
                'notelp' => '08123456908',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert data ke dalam tabel users
        DB::table('users')->insert($usersData);

        $this->command->info('Seeder User berhasil dijalankan!');
    }
}
