<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $usersData = [
            // Keluarga 1
            [
                'nik' => '3573072506850001',
                'nama' => 'Budi Santoso',
                'tgl_lahir' => '1985-06-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Guru',
                'notelp' => '081234567891',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071505900002',
                'nama' => 'Aril Saputra',
                'tgl_lahir' => '1990-05-15',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Karyawan',
                'notelp' => '081234567890',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075507800003',
                'nama' => 'Citra Lestari',
                'tgl_lahir' => '1980-07-15',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '081234567892',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075002950004',
                'nama' => 'Dewi Sari',
                'tgl_lahir' => '1995-02-10',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pengacara',
                'notelp' => '081234567893',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 2
            [
                'nik' => '3573071703650005',
                'nama' => 'Gilang Maulana',
                'tgl_lahir' => '1965-03-17',
                'tempat_lahir' => 'Kediri',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Petani',
                'notelp' => '081234567896',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072509700006',
                'nama' => 'Eko Prasetyo',
                'tgl_lahir' => '1970-09-25',
                'tempat_lahir' => 'Surabaya',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Insinyur',
                'notelp' => '081234567894',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074401800007',
                'nama' => 'Fitri Andayani',
                'tgl_lahir' => '1980-01-04',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pedagang',
                'notelp' => '081234567895',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076208900008',
                'nama' => 'Hana Kartika',
                'tgl_lahir' => '1990-08-22',
                'tempat_lahir' => 'Jakarta',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Penulis',
                'notelp' => '081234567897',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 3
            [
                'nik' => '3573071302750009',
                'nama' => 'Irwan Saputra',
                'tgl_lahir' => '1975-02-13',
                'tempat_lahir' => 'Denpasar',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Supir',
                'notelp' => '081234567898',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072906850010',
                'nama' => 'Joko Winarno',
                'tgl_lahir' => '1985-06-29',
                'tempat_lahir' => 'Singaraja',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Nelayan',
                'notelp' => '081234567899',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075401750011',
                'nama' => 'Kartika Dewi',
                'tgl_lahir' => '1975-01-14',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '081234567810',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070407800012',
                'nama' => 'Lukman Hakim',
                'tgl_lahir' => '1980-07-04',
                'tempat_lahir' => 'Bandung',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '081234567811',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 4
            [
                'nik' => '3573072403700013',
                'nama' => 'Oktavianus Aditya',
                'tgl_lahir' => '1970-03-24',
                'tempat_lahir' => 'Jakarta',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Seniman',
                'notelp' => '081234567814',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573077104800014',
                'nama' => 'Mega Astuti',
                'tgl_lahir' => '1980-04-30',
                'tempat_lahir' => 'Tuban',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Arsitek',
                'notelp' => '081234567812',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074908750015',
                'nama' => 'Nina Fitriani',
                'tgl_lahir' => '1975-08-09',
                'tempat_lahir' => 'Jombang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Penyiar',
                'notelp' => '081234567813',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076909800016',
                'nama' => 'Putri Agustina',
                'tgl_lahir' => '1980-09-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Wartawan',
                'notelp' => '081234567815',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 5
            [
                'nik' => '3573071806750017',
                'nama' => 'Ridwan Santoso',
                'tgl_lahir' => '1975-06-18',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '081234567816',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074702800018',
                'nama' => 'Sari Putri',
                'tgl_lahir' => '1980-02-07',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Banker',
                'notelp' => '081234567817',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072201800019',
                'nama' => 'Taufik Rahman',
                'tgl_lahir' => '1980-01-22',
                'tempat_lahir' => 'Surabaya',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Programmer',
                'notelp' => '081234567818',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074103850020',
                'nama' => 'Umi Kalsum',
                'tgl_lahir' => '1985-03-01',
                'tempat_lahir' => 'Batam',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelukis',
                'notelp' => '081234567819',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 6
            [
                'nik' => '3573070107800021',
                'nama' => 'Arief Setiawan',
                'tgl_lahir' => '1980-07-01',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Buruh',
                'notelp' => '081234567823',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074103850022',
                'nama' => 'Wulan Septiani',
                'tgl_lahir' => '1985-03-01',
                'tempat_lahir' => 'Bandung',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Akuntan',
                'notelp' => '081234567820',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071504900023',
                'nama' => 'Yudi Pratama',
                'tgl_lahir' => '1990-04-15',
                'tempat_lahir' => 'Singaraja',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Arsitek',
                'notelp' => '081234567821',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076502950024',
                'nama' => 'Zara Indah',
                'tgl_lahir' => '1995-02-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Asisten Rumah Tangga',
                'notelp' => '081234567822',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 7
            [
                'nik' => '3573070503750025',
                'nama' => 'Gunawan Budiman',
                'tgl_lahir' => '1975-03-05',
                'tempat_lahir' => 'Padang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Ekonom',
                'notelp' => '081234567827',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076208900026',
                'nama' => 'Diana Rachmawati',
                'tgl_lahir' => '1990-08-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Desainer Grafis',
                'notelp' => '081234567824',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070204950027',
                'nama' => 'Edi Kurniawan',
                'tgl_lahir' => '1995-04-02',
                'tempat_lahir' => 'Medan',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Dosen',
                'notelp' => '081234567825',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074809800028',
                'nama' => 'Fitria Maulida',
                'tgl_lahir' => '1980-09-08',
                'tempat_lahir' => 'Palembang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Editor',
                'notelp' => '081234567826',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 8
            [
                'nik' => '3573070607850029',
                'nama' => 'Indra Wijaya',
                'tgl_lahir' => '1985-07-06',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Geolog',
                'notelp' => '081234567829',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076904800030',
                'nama' => 'Heni Astuti',
                'tgl_lahir' => '1980-04-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Fotografer',
                'notelp' => '081234567828',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075906750031',
                'nama' => 'Lia Cahyani',
                'tgl_lahir' => '1975-06-19',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Guru',
                'notelp' => '081234567830',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072301800032',
                'nama' => 'Dodi Pranata',
                'tgl_lahir' => '1980-01-23',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '081234567831',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 9
            [
                'nik' => '3573071301800033',
                'nama' => 'Bambang Suryanto',
                'tgl_lahir' => '1980-01-13',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Arsitek',
                'notelp' => '081234567835',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076004850034',
                'nama' => 'Rina Novitasari',
                'tgl_lahir' => '1985-04-20',
                'tempat_lahir' => 'Yogyakarta',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '081234567832',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070505900035',
                'nama' => 'Denny Setiawan',
                'tgl_lahir' => '1990-05-05',
                'tempat_lahir' => 'Bandung',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pengacara',
                'notelp' => '081234567833',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076808950036',
                'nama' => 'Siska Anggraini',
                'tgl_lahir' => '1995-08-28',
                'tempat_lahir' => 'Magelang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Programmer',
                'notelp' => '081234567834',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 10
            [
                'nik' => '3573071101750037',
                'nama' => 'Rudi Hidayat',
                'tgl_lahir' => '1975-01-11',
                'tempat_lahir' => 'Gorontalo',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Guru',
                'notelp' => '081234567837',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076407950038',
                'nama' => 'Ani Wahyuni',
                'tgl_lahir' => '1995-07-24',
                'tempat_lahir' => 'Makassar',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '081234567836',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075702800039',
                'nama' => 'Rina Wulandari',
                'tgl_lahir' => '1980-02-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '081234567838',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072907850040',
                'nama' => 'Ahmad Yani',
                'tgl_lahir' => '1985-07-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pengusaha',
                'notelp' => '081234567839',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 11
            [
                'nik' => '3573070803950041',
                'nama' => 'Agus Kuswanto',
                'tgl_lahir' => '1995-03-08',
                'tempat_lahir' => 'Serang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wirausaha',
                'notelp' => '081234567841',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074303900042',
                'nama' => 'Diana Fitriani',
                'tgl_lahir' => '1990-03-03',
                'tempat_lahir' => 'Kupang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pegawai Swasta',
                'notelp' => '081234567840',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076005000043',
                'nama' => 'Sari Widya',
                'tgl_lahir' => '2000-05-20',
                'tempat_lahir' => 'Bengkulu',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567842',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072809000044',
                'nama' => 'Agung Nugroho',
                'tgl_lahir' => '2000-09-28',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567843',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 12
            [
                'nik' => '3573070606100045',
                'nama' => 'Wahyu Firmansyah',
                'tgl_lahir' => '2010-06-06',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567847',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074205050046',
                'nama' => 'Dewi Lestari',
                'tgl_lahir' => '2005-05-02',
                'tempat_lahir' => 'Pekanbaru',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567844',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071009100047',
                'nama' => 'Taufik Hidayat',
                'tgl_lahir' => '2010-09-10',
                'tempat_lahir' => 'Kendari',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567845',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076401050048',
                'nama' => 'Ani Rahayu',
                'tgl_lahir' => '2005-01-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567846',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 13
            [
                'nik' => '3573072305060049',
                'nama' => 'Rizky Ramadhan',
                'tgl_lahir' => '2006-05-23',
                'tempat_lahir' => 'Jambi',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567849',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075901070050',
                'nama' => 'Nia Fitriani',
                'tgl_lahir' => '2007-01-19',
                'tempat_lahir' => 'Payakumbuh',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567848',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076801100051',
                'nama' => 'Rini Susanti',
                'tgl_lahir' => '2010-01-28',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567850',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071706150052',
                'nama' => 'Firman Wijaya',
                'tgl_lahir' => '2015-06-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567851',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 14
            [
                'nik' => '3573073005160053',
                'nama' => 'Dodi Wijaya',
                'tgl_lahir' => '2016-05-30',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567855',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075405200054',
                'nama' => 'Sinta Purnama',
                'tgl_lahir' => '2020-05-14',
                'tempat_lahir' => 'Sabang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567852',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070803200055',
                'nama' => 'Budi Susanto',
                'tgl_lahir' => '2020-03-08',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567853',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076503150056',
                'nama' => 'Sari Puspita',
                'tgl_lahir' => '2015-03-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567854',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 15
            [
                'nik' => '3573073006050057',
                'nama' => 'Doni Setiawan',
                'tgl_lahir' => '2005-06-30',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567859',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075409200058',
                'nama' => 'Lina Wulandari',
                'tgl_lahir' => '2020-09-14',
                'tempat_lahir' => 'Jayapura',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567856',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072108100059',
                'nama' => 'Adi Pratama',
                'tgl_lahir' => '2010-08-21',
                'tempat_lahir' => 'Kediri',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567857',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075904100060',
                'nama' => 'Ani Maulida',
                'tgl_lahir' => '2010-04-19',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567858',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 16
            [
                'nik' => '3573072704750061',
                'nama' => 'Andi Pranata',
                'tgl_lahir' => '1975-04-27',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '081234567861',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075005700062',
                'nama' => 'Rina Sari',
                'tgl_lahir' => '1970-05-10',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Guru',
                'notelp' => '081234567860',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075401800063',
                'nama' => 'Lina Septiani',
                'tgl_lahir' => '1980-01-14',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Insinyur',
                'notelp' => '081234567862',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072909850064',
                'nama' => 'Dodi Setiawan',
                'tgl_lahir' => '1985-09-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Akuntan',
                'notelp' => '081234567863',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 17
            [
                'nik' => '3573071504950065',
                'nama' => 'Ari Kurniawan',
                'tgl_lahir' => '1995-04-15',
                'tempat_lahir' => 'Medan',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wirausaha',
                'notelp' => '081234567865',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074303900066',
                'nama' => 'Siti Wulandari',
                'tgl_lahir' => '1990-03-03',
                'tempat_lahir' => 'Ambon',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Programmer',
                'notelp' => '081234567864',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074708000067',
                'nama' => 'Dini Hidayati',
                'tgl_lahir' => '2000-08-07',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567866',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071909050068',
                'nama' => 'Firman Nugroho',
                'tgl_lahir' => '2005-09-19',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567867',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 18
            [
                'nik' => '3573073103150069',
                'nama' => 'Dedi Ramadhan',
                'tgl_lahir' => '2015-03-31',
                'tempat_lahir' => 'Surabaya',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567869',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076705100070',
                'nama' => 'Rina Setiawati',
                'tgl_lahir' => '2010-05-27',
                'tempat_lahir' => 'Bandung',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567868',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075608150071',
                'nama' => 'Siti Rahmawati',
                'tgl_lahir' => '2015-08-16',
                'tempat_lahir' => 'Surabaya',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567870',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070905200072',
                'nama' => 'Bayu Kusuma',
                'tgl_lahir' => '2020-05-09',
                'tempat_lahir' => 'Kediri',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567871',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 19
            [
                'nik' => '3573073101100073',
                'nama' => 'Dedi Susanto',
                'tgl_lahir' => '2010-01-31',
                'tempat_lahir' => 'Batam',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567873',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076409200074',
                'nama' => 'Lina Wijaya',
                'tgl_lahir' => '2020-09-24',
                'tempat_lahir' => 'Batam',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567872',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074404150075',
                'nama' => 'Rina Astuti',
                'tgl_lahir' => '2015-04-04',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567874',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070808200076',
                'nama' => 'Budi Wijaya',
                'tgl_lahir' => '2020-08-08',
                'tempat_lahir' => 'Blitar',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567875',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 20
            [
                'nik' => '3573072909000077',
                'nama' => 'Agus Pratama',
                'tgl_lahir' => '2000-09-29',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567877',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076502050078',
                'nama' => 'Siti Rahayu',
                'tgl_lahir' => '2005-02-25',
                'tempat_lahir' => 'Probolinggo',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567876',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074407140079',
                'nama' => 'Diana Susanti',
                'tgl_lahir' => '2014-07-04',
                'tempat_lahir' => 'Probolinggo',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567878',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071801060080',
                'nama' => 'Rudi Pranata',
                'tgl_lahir' => '2006-01-18',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567879',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 21
            [
                'nik' => '3573072203700081',
                'nama' => 'Agus Kusuma',
                'tgl_lahir' => '1970-03-22',
                'tempat_lahir' => 'Probolinggo',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '081234567881',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075405650082',
                'nama' => 'Sari Setiawan',
                'tgl_lahir' => '1965-05-14',
                'tempat_lahir' => 'Surabaya',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'notelp' => '081234567880',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074808750083',
                'nama' => 'Dewi Wulandari',
                'tgl_lahir' => '1975-08-08',
                'tempat_lahir' => 'Kediri',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Guru',
                'notelp' => '081234567882',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573073009800084',
                'nama' => 'Budi Santoso',
                'tgl_lahir' => '1980-09-30',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '081234567883',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 22
            [
                'nik' => '3573070101900085',
                'nama' => 'Dedi Firmansyah',
                'tgl_lahir' => '1990-01-01',
                'tempat_lahir' => 'Magelang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '081234567885',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075104850086',
                'nama' => 'Siti Hartati',
                'tgl_lahir' => '1985-04-11',
                'tempat_lahir' => 'Yogyakarta',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '081234567884',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076301950087',
                'nama' => 'Rina Setiawan',
                'tgl_lahir' => '1995-01-23',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pegawai Negeri',
                'notelp' => '081234567886',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072901000088',
                'nama' => 'Dodi Pranata',
                'tgl_lahir' => '2000-01-29',
                'tempat_lahir' => 'Kediri',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567887',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 23
            [
                'nik' => '3573070503100089',
                'nama' => 'Agus Kurniawan',
                'tgl_lahir' => '2010-03-05',
                'tempat_lahir' => 'Samarinda',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567889',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075006050090',
                'nama' => 'Sari Wulandari',
                'tgl_lahir' => '2005-06-10',
                'tempat_lahir' => 'Pontianak',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567888',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074402150091',
                'nama' => 'Siti Maryati',
                'tgl_lahir' => '2015-02-04',
                'tempat_lahir' => 'Medan',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567890',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072907200092',
                'nama' => 'Rudi Setiawan',
                'tgl_lahir' => '2020-07-29',
                'tempat_lahir' => 'Batam',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567891',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 24
            [
                'nik' => '3573070101030093',
                'nama' => 'Dodi Wijaya',
                'tgl_lahir' => '2003-01-01',
                'tempat_lahir' => 'Riau',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567893',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075708200094',
                'nama' => 'Sari Astuti',
                'tgl_lahir' => '2020-08-17',
                'tempat_lahir' => 'Riau',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567892',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076302130095',
                'nama' => 'Rina Wulandari',
                'tgl_lahir' => '2013-02-23',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567894',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071002040096',
                'nama' => 'Budi Pratama',
                'tgl_lahir' => '2004-02-10',
                'tempat_lahir' => 'Pekanbaru',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567895',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 25
            [
                'nik' => '3573073109060097',
                'nama' => 'Dedi Santoso',
                'tgl_lahir' => '2006-09-30',
                'tempat_lahir' => 'Singaraja',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567897',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076803140098',
                'nama' => 'Siti Wijaya',
                'tgl_lahir' => '2014-03-28',
                'tempat_lahir' => 'Denpasar',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567896',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075401160099',
                'nama' => 'Rina Pratiwi',
                'tgl_lahir' => '2016-01-14',
                'tempat_lahir' => 'Tabanan',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567898',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071703170100',
                'nama' => 'Budi Setiawan',
                'tgl_lahir' => '2017-03-17',
                'tempat_lahir' => 'Badung',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567899',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 26
            [
                'nik' => '3573072202700101',
                'nama' => 'Agus Setiawan',
                'tgl_lahir' => '1970-02-22',
                'tempat_lahir' => 'Singaraja',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '081234567801',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075306650102',
                'nama' => 'Siti Rahmawati',
                'tgl_lahir' => '1965-06-13',
                'tempat_lahir' => 'Bandung',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'notelp' => '081234567800',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074707750103',
                'nama' => 'Dewi Kusuma',
                'tgl_lahir' => '1975-07-07',
                'tempat_lahir' => 'Bandung',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Guru',
                'notelp' => '081234567802',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573072507800104',
                'nama' => 'Budi Santoso',
                'tgl_lahir' => '1980-07-25',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 2,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'PNS',
                'notelp' => '081234567803',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 27
            [
                'nik' => '3573072204900105',
                'nama' => 'Dedi Setiawan',
                'tgl_lahir' => '1990-04-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'notelp' => '081234567805',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075707850106',
                'nama' => 'Sari Kurniawan',
                'tgl_lahir' => '1985-07-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'notelp' => '081234567804',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076405950107',
                'nama' => 'Rina Wijaya',
                'tgl_lahir' => '1995-05-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Guru',
                'notelp' => '081234567806',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573071706000108',
                'nama' => 'Agus Pratama',
                'tgl_lahir' => '2000-06-17',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 3,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567807',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 28
            [
                'nik' => '3573072902100109',
                'nama' => 'Budi Santoso',
                'tgl_lahir' => '2010-02-28',
                'tempat_lahir' => 'Pekanbaru',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567809',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074408050110',
                'nama' => 'Siti Indah',
                'tgl_lahir' => '2005-08-04',
                'tempat_lahir' => 'Riau',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567808',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074203150111',
                'nama' => 'Rina Susanti',
                'tgl_lahir' => '2015-03-02',
                'tempat_lahir' => 'Probolinggo',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567810',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070704200112',
                'nama' => 'Budi Wijaya',
                'tgl_lahir' => '2020-04-07',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 4,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567811',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 29
            [
                'nik' => '3573072203010113',
                'nama' => 'Budi Pratama',
                'tgl_lahir' => '2001-03-22',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567815',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573075809200114',
                'nama' => 'Sari Kusuma',
                'tgl_lahir' => '2020-09-18',
                'tempat_lahir' => 'Kediri',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567812',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070809200115',
                'nama' => 'Dedi Santoso',
                'tgl_lahir' => '2020-09-08',
                'tempat_lahir' => 'Kediri',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 5,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Belum Bekerja',
                'notelp' => '081234567813',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573076405020116',
                'nama' => 'Rina Kurniawan',
                'tgl_lahir' => '2002-05-24',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 5,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567814',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Keluarga 30
            [
                'nik' => '3573073103070117',
                'nama' => 'Agus Santoso',
                'tgl_lahir' => '2007-03-31',
                'tempat_lahir' => 'Blitar',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567817',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074709040118',
                'nama' => 'Sari Wijaya',
                'tgl_lahir' => '2004-09-07',
                'tempat_lahir' => 'Tuban',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Kawin',
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '081234567816',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573074904080119',
                'nama' => 'Dewi Setiawan',
                'tgl_lahir' => '2008-04-09',
                'tempat_lahir' => 'Blitar',
                'jenis_kelamin' => 'Perempuan',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567818',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nik' => '3573070105090120',
                'nama' => 'Rudi Pratama',
                'tgl_lahir' => '2009-05-01',
                'tempat_lahir' => 'Malang',
                'jenis_kelamin' => 'Laki',
                'agama_id' => 6,
                'status_perkawinan' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'notelp' => '081234567819',
                'keluarga_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert data ke dalam tabel users
        DB::table('users')->insert($usersData);

        $this->command->info('Seeder User berhasil dijalankan!');
    }
}
